plugins {
    id 'com.android.application'
}

android {
    namespace "co.zw.zivvvo"
    compileSdk 34
    buildToolsVersion "34.0.0"

    defaultConfig {
        applicationId "co.zw.zivvvo"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    signingConfigs {
        release {
            storeFile file("release-key.jks")
            storePassword System.getenv("STORE_PASSWORD") ?: "Zivvvo2026!"
            keyAlias "zivvvo"
            keyPassword System.getenv("KEY_PASSWORD") ?: "Zivvvo2026!"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.browser:browser:1.7.0'
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.4.0'
    implementation 'androidx.core:core-splashscreen:1.0.1'
}
